@javascript @smoke
Feature: Test edit pages for javascript errors, differing settings can cause different issues
#We have added Javascript tests to all pages tested so for now we just have to visit pages that do not have tests on them already. Currently using test UPO as an approximate user

  @now1
  Scenario: I go to all the Enter pages Then see if there are javascript errors present. Users generally don't edit
    Given I login as UPO
    And I am on "my_research_add.php"
    And I select "Audio Document" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Book" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Book Chapter" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Conference Paper" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Conference Proceedings" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Creative Work" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Department Technical Report" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Design" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Digilib Image" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Generic Document" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Image" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Journal" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Journal Article" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Newspaper Article" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Patent" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Preprint" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Reference Entry" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Research Report" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Seminar Paper" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Thesis" from "xdis_id_top"
    And I press "Next"
    And I follow "Student Submission of Thesis"
    And I am on "my_research_add.php"
    And I select "Video Document" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I select "Working Paper" from "xdis_id_top"
    And I press "Next"
    And I am on "my_research_add.php"
    And I follow "Add Missing Data Collection"



