ALTER TABLE %TABLE_PREFIX%exif DROP PRIMARY KEY;
ALTER TABLE %TABLE_PREFIX%exif ADD COLUMN exif_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE %TABLE_PREFIX%exif ADD UNIQUE KEY exif_idx (exif_pid, exif_dsid);
