FROM uqlibrary/docker-fpm56-fez:18

RUN rm -f /etc/php.d/15-xdebug.ini

WORKDIR /var/app/current/
COPY . /var/app/current/

COPY ./.docker/testing/config.inc.php /var/app/current/public/config.inc.php

ENTRYPOINT ["/bin/bash"]