FROM uqlibrary/docker-fpm56:5

WORKDIR /var/app/current/
COPY . /var/app/current/

RUN rm -f /etc/php.d/15-xdebug.ini

COPY ./.docker/testing/config.inc.php /var/app/current/public/config.inc.php

ENTRYPOINT ["/bin/bash"]
