-- Convert a Fez MySQL database from MyISAM to mostly InnoDB
-- Author: Jonathan Harker, Catalyst IT for RMIT
-- Date:   11 November 2010

alter table fez_user engine=MyISAM;
alter table fez_author engine=MyISAM;
alter table fez_background_process engine=MyISAM;

drop index ar_rule on fez_auth_rules;
drop index rmf_varchar on fez_record_matching_field;
drop index rek_description on fez_record_search_key;
drop index rek_fulltext on fez_record_search_key;
drop index rek_fulltext_all on fez_record_search_key;
drop index rek_title_ft on fez_record_search_key;
drop index rek_keywords_fulltext on fez_record_search_key_keywords;
drop index rek_na_explanation on fez_record_search_key_na_explanation;
drop index rek_notes on fez_record_search_key_notes;
drop index rek_sensitivity_explanation on fez_record_search_key_sensitivity_explanation;
drop index xsdmf_element on fez_xsd_display_matchfields;

alter table fez_ad_hoc_sql engine=InnoDB;
alter table fez_auth_index2 engine=InnoDB;
alter table fez_auth_index2_lister engine=InnoDB;
alter table fez_auth_index2_pre_fez2_upgrade engine=InnoDB;
alter table fez_author_affiliation engine=InnoDB;
alter table fez_author_classification engine=InnoDB;
alter table fez_author_function engine=InnoDB;
alter table fez_author_org_structure engine=InnoDB;
alter table fez_auth_quick_template engine=InnoDB;
alter table fez_auth_roles engine=InnoDB;
alter table fez_auth_rule_group_rules engine=InnoDB;
alter table fez_auth_rule_groups engine=InnoDB;
alter table fez_auth_rule_group_users engine=InnoDB;
alter table fez_auth_rules engine=InnoDB;
alter table fez_background_process_pids engine=InnoDB;
alter table fez_citation engine=InnoDB;
alter table fez_cloud_tag engine=InnoDB;
alter table fez_conference engine=InnoDB;
alter table fez_config engine=InnoDB;
alter table fez_controlled_vocab engine=InnoDB;
alter table fez_controlled_vocab_relationship engine=InnoDB;
alter table fez_custom_views_community engine=InnoDB;
alter table fez_custom_views engine=InnoDB;
alter table fez_custom_views_search_keys engine=InnoDB;
alter table fez_eprints_import_pids engine=InnoDB;
alter table fez_exif engine=InnoDB;
alter table fez_fez_google_scholar_citations engine=InnoDB;
alter table fez_fulltext_cache engine=InnoDB;
alter table fez_fulltext_engine engine=InnoDB;
alter table fez_fulltext_index engine=InnoDB;
alter table fez_fulltext_keywords engine=InnoDB;
alter table fez_fulltext_locks engine=InnoDB;
alter table fez_fulltext_queue engine=InnoDB;
alter table fez_geocode_cities engine=InnoDB;
alter table fez_geocode_country engine=InnoDB;
alter table fez_geocode_location_cache engine=InnoDB;
alter table fez_geocode_regions engine=InnoDB;
alter table fez_google_scholar_citations engine=InnoDB;
alter table fez_group engine=InnoDB;
alter table fez_group_user engine=InnoDB;
alter table fez_integrity_index_ghosts engine=InnoDB;
alter table fez_integrity_pid_auth_ghosts engine=InnoDB;
alter table fez_integrity_solr_ghosts engine=InnoDB;
alter table fez_integrity_solr_unspawned_citations engine=InnoDB;
alter table fez_integrity_solr_unspawned engine=InnoDB;
alter table fez_internal_notes engine=InnoDB;
alter table fez_journal engine=InnoDB;
alter table fez_journal_issns engine=InnoDB;
alter table fez_language engine=InnoDB;
alter table fez_mail_queue engine=InnoDB;
alter table fez_mail_queue_log engine=InnoDB;
alter table fez_main_chapter engine=InnoDB;
alter table fez_my_research_claimed_flagged engine=InnoDB;
alter table fez_my_research_possible_flagged engine=InnoDB;
alter table fez_news engine=InnoDB;
alter table fez_object_type engine=InnoDB;
alter table fez_org_structure engine=InnoDB;
alter table fez_org_structure_relationship engine=InnoDB;
alter table fez_premis_event engine=InnoDB;
alter table fez_recently_added_items engine=InnoDB;
alter table fez_recently_downloaded_items engine=InnoDB;
alter table fez_record_locks engine=InnoDB;
alter table fez_record_matching_field engine=InnoDB;
alter table fez_record_search_key_alternative_title engine=InnoDB;
alter table fez_record_search_key_anglicised_publisher engine=InnoDB;
alter table fez_record_search_key_anglicised_title engine=InnoDB;
alter table fez_record_search_key_assigned_group_id engine=InnoDB;
alter table fez_record_search_key_assigned_user_id engine=InnoDB;
alter table fez_record_search_key_author engine=InnoDB;
alter table fez_record_search_key_author_id engine=InnoDB;
alter table fez_record_search_key_book_title engine=InnoDB;
alter table fez_record_search_key_chapter_number engine=InnoDB;
alter table fez_record_search_key_conference_dates engine=InnoDB;
alter table fez_record_search_key_conference_location engine=InnoDB;
alter table fez_record_search_key_conference_name engine=InnoDB;
alter table fez_record_search_key_contributor engine=InnoDB;
alter table fez_record_search_key_contributor_id engine=InnoDB;
alter table fez_record_search_key_convener engine=InnoDB;
alter table fez_record_search_key_country_of_issue engine=InnoDB;
alter table fez_record_search_key_date_available engine=InnoDB;
alter table fez_record_search_key_edition engine=InnoDB;
alter table fez_record_search_key_end_page engine=InnoDB;
alter table fez_record_search_key engine=InnoDB;
alter table fez_record_search_key_english_publisher engine=InnoDB;
alter table fez_record_search_key_english_title engine=InnoDB;
alter table fez_record_search_key_file_attachment_content engine=InnoDB;
alter table fez_record_search_key_file_attachment_name engine=InnoDB;
alter table fez_record_search_key_file_downloads engine=InnoDB;
alter table fez_record_search_key_first_author_in_document_derived engine=InnoDB;
alter table fez_record_search_key_first_author_in_fez_derived engine=InnoDB;
alter table fez_record_search_key_identifier engine=InnoDB;
alter table fez_record_search_key_isannotationof engine=InnoDB;
alter table fez_record_search_key_isbn engine=InnoDB;
alter table fez_record_search_key_isdatacomponentof engine=InnoDB;
alter table fez_record_search_key_isderivationof engine=InnoDB;
alter table fez_record_search_key_isi_loc engine=InnoDB;
alter table fez_record_search_key_ismemberof engine=InnoDB;
alter table fez_record_search_key_issn engine=InnoDB;
alter table fez_record_search_key_issue_number engine=InnoDB;
alter table fez_record_search_key_journal_name engine=InnoDB;
alter table fez_record_search_key_keywords engine=InnoDB;
alter table fez_record_search_key_language engine=InnoDB;
alter table fez_record_search_key_language_of_title engine=InnoDB;
alter table fez_record_search_key_link_description engine=InnoDB;
alter table fez_record_search_key_link engine=InnoDB;
alter table fez_record_search_key_na_explanation engine=InnoDB;
alter table fez_record_search_key_newspaper engine=InnoDB;
alter table fez_record_search_key_notes engine=InnoDB;
alter table fez_record_search_key_org_name engine=InnoDB;
alter table fez_record_search_key_org_unit_name engine=InnoDB;
alter table fez_record_search_key_output_availability engine=InnoDB;
alter table fez_record_search_key_parent_publication engine=InnoDB;
alter table fez_record_search_key_phonetic_book_title engine=InnoDB;
alter table fez_record_search_key_phonetic_conference_name engine=InnoDB;
alter table fez_record_search_key_phonetic_journal_name engine=InnoDB;
alter table fez_record_search_key_phonetic_newspaper engine=InnoDB;
alter table fez_record_search_key_phonetic_title engine=InnoDB;
alter table fez_record_search_key_place_of_publication engine=InnoDB;
alter table fez_record_search_key_prn engine=InnoDB;
alter table fez_record_search_key_proceedings_title engine=InnoDB;
alter table fez_record_search_key_publisher engine=InnoDB;
alter table fez_record_search_key_refereed engine=InnoDB;
alter table fez_record_search_key_report_number engine=InnoDB;
alter table fez_record_search_key_research_program engine=InnoDB;
alter table fez_record_search_key_rights engine=InnoDB;
alter table fez_record_search_key_scopus_id engine=InnoDB;
alter table fez_record_search_key_sensitivity_explanation engine=InnoDB;
alter table fez_record_search_key_series engine=InnoDB;
alter table fez_record_search_key_start_page engine=InnoDB;
alter table fez_record_search_key_subject engine=InnoDB;
alter table fez_record_search_key_translated_book_title engine=InnoDB;
alter table fez_record_search_key_translated_conference_name engine=InnoDB;
alter table fez_record_search_key_translated_journal_name engine=InnoDB;
alter table fez_record_search_key_translated_newspaper engine=InnoDB;
alter table fez_record_search_key_translated_title engine=InnoDB;
alter table fez_record_search_key_volume_number engine=InnoDB;
alter table fez_record_search_key_xsd_display_option engine=InnoDB;
alter table fez_rid_jobs engine=InnoDB;
alter table fez_scopus_citations engine=InnoDB;
alter table fez_search_key engine=InnoDB;
alter table fez_sessions engine=InnoDB;
alter table fez_statistics_all engine=InnoDB;
alter table fez_statistics_buffer engine=InnoDB;
alter table fez_statistics_proc engine=InnoDB;
alter table fez_statistics_robots engine=InnoDB;
alter table fez_statistics_sum_4weeks engine=InnoDB;
alter table fez_statistics_sum_authors engine=InnoDB;
alter table fez_statistics_sum_countryregion engine=InnoDB;
alter table fez_statistics_sum_papers engine=InnoDB;
alter table fez_statistics_sum_year engine=InnoDB;
alter table fez_statistics_sum_yearmonth engine=InnoDB;
alter table fez_statistics_sum_yearmonth_figures engine=InnoDB;
alter table fez_status engine=InnoDB;
alter table fez_survey engine=InnoDB;
alter table fez_thomson_citations engine=InnoDB;
alter table fez_user_comments engine=InnoDB;
alter table fez_user_shibboleth_attribs engine=InnoDB;
alter table fez_wfbehaviour engine=InnoDB;
alter table fez_workflow engine=InnoDB;
alter table fez_workflow_roles engine=InnoDB;
alter table fez_workflow_sessions engine=InnoDB;
alter table fez_workflow_state engine=InnoDB;
alter table fez_workflow_state_link engine=InnoDB;
alter table fez_workflow_state_roles engine=InnoDB;
alter table fez_workflow_trigger engine=InnoDB;
alter table fez_xsd_display_attach engine=InnoDB;
alter table fez_xsd_display engine=InnoDB;
alter table fez_xsd_display_matchfields engine=InnoDB;
alter table fez_xsd_display_mf_option engine=InnoDB;
alter table fez_xsd engine=InnoDB;
alter table fez_xsd_loop_subelement engine=InnoDB;
alter table fez_xsd_relationship engine=InnoDB;

update fez_config set config_value='ON' where config_name='app_mysql_innodb_flag';

