CREATE TABLE fez_record_search_key__shadow (
  rek_pid varchar(64) NOT NULL COMMENT 'PID',
  rek_title_xsdmf_id int(11) DEFAULT NULL,
  rek_title varchar(1000) DEFAULT NULL COMMENT 'Title',
  rek_description_xsdmf_id int(11) DEFAULT NULL,
  rek_description text COMMENT 'Description',
  rek_display_type_xsdmf_id int(11) DEFAULT NULL,
  rek_display_type int(11) DEFAULT NULL COMMENT 'Display Type',
  rek_status_xsdmf_id int(11) DEFAULT NULL,
  rek_status int(11) DEFAULT NULL COMMENT 'Status',
  rek_date_xsdmf_id int(11) DEFAULT NULL,
  rek_date datetime DEFAULT NULL COMMENT 'Date',
  rek_object_type_xsdmf_id int(11) DEFAULT NULL,
  rek_object_type int(11) DEFAULT NULL COMMENT 'Object Type',
  rek_depositor_xsdmf_id int(11) DEFAULT NULL,
  rek_depositor int(11) DEFAULT NULL COMMENT 'Depositor',
  rek_created_date_xsdmf_id int(11) DEFAULT NULL,
  rek_created_date datetime DEFAULT NULL COMMENT 'Created Date',
  rek_updated_date_xsdmf_id int(11) DEFAULT NULL,
  rek_updated_date datetime DEFAULT NULL COMMENT 'Updated Date',
  rek_file_downloads int(11) DEFAULT '0',
  rek_views int(11) DEFAULT '0',
  rek_citation text,
  rek_sequence int(11) DEFAULT '0' COMMENT 'Sequence order in a parent object',
  rek_sequence_xsdmf_id int(11) DEFAULT NULL,
  rek_genre_xsdmf_id int(11) DEFAULT NULL,
  rek_genre varchar(255) DEFAULT NULL COMMENT 'Genre',
  rek_genre_type_xsdmf_id int(11) DEFAULT NULL,
  rek_genre_type varchar(255) DEFAULT NULL COMMENT 'Genre Type',
  rek_formatted_title_xsdmf_id int(11) DEFAULT NULL,
  rek_formatted_title text COMMENT 'Formatted Title',
  rek_formatted_abstract_xsdmf_id int(11) DEFAULT NULL,
  rek_formatted_abstract text COMMENT 'Formatted Abstract',
  rek_depositor_affiliation_xsdmf_id int(11) DEFAULT NULL,
  rek_depositor_affiliation int(11) DEFAULT NULL,
  rek_thomson_citation_count int(11) DEFAULT NULL,
  rek_gs_citation_count int(4) DEFAULT NULL,
  rek_gs_cited_by_link text,
  rek_thomson_citation_count_xsdmf_id int(11) DEFAULT NULL,
  rek_subtype_xsdmf_id int(11) DEFAULT NULL,
  rek_subtype varchar(255) DEFAULT NULL,
  rek_scopus_citation_count int(11) DEFAULT NULL,
  rek_herdc_notes_xsdmf_id int(11) DEFAULT NULL,
  rek_herdc_notes text,
  rek_scopus_doc_type_xsdmf_id int(11) DEFAULT NULL,
  rek_scopus_doc_type varchar(255) DEFAULT NULL,
  rek_wok_doc_type_xsdmf_id int(11) DEFAULT NULL,
  rek_wok_doc_type varchar(255) DEFAULT NULL,
  rek_stamp datetime DEFAULT NULL,
  KEY rek_display_type (rek_display_type),
  KEY rek_status (rek_status),
  KEY rek_date (rek_date),
  KEY rek_object_type (rek_object_type),
  KEY rek_depositor (rek_depositor),
  KEY rek_created_date (rek_created_date),
  KEY rek_updated_date (rek_updated_date),
  KEY rek_title (rek_title(255)),
  KEY rek_views (rek_views),
  KEY rek_file_downloads (rek_file_downloads),
  KEY rek_sequence (rek_sequence),
  KEY rek_genre (rek_genre),
  KEY rek_genre_type (rek_genre_type),
  KEY rek_subtype (rek_subtype)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;