CREATE TABLE `%TABLE_PREFIX%author__shadow` (
  `aut_id` int(11) NOT NULL,
  `aut_org_username` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_org_staff_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_org_student_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_display_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_fname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_mname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_lname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_position` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_homepage_link` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_created_date` date DEFAULT NULL,
  `aut_update_date` date DEFAULT NULL,
  `aut_external_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_ref_num` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_researcher_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_scopus_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_mypub_url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_rid_password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_people_australia_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_description` text COLLATE utf8_unicode_ci,
  `aut_orcid_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_google_scholar_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_rid_last_updated` date DEFAULT NULL,
  `aut_publons_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_student_username` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aut_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aut_version` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `aut_source` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'master',
  `aut_source_checksum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  KEY `aut_fulltext` (`aut_fname`,`aut_lname`),
  KEY `aut_org_username_2` (`aut_org_username`),
  KEY `aut_org_staff_id` (`aut_org_staff_id`),
  KEY `aut_org_student_id` (`aut_org_student_id`),
  KEY `aut_display_name` (`aut_display_name`),
  KEY `aut_fname` (`aut_fname`),
  KEY `aut_lname_2` (`aut_lname`),
  KEY `aut_student_username_ft` (`aut_student_username`),
  KEY `aut_source` (`aut_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
